<?php
// This file is generated by maintenance/generateJsonI18n.php. Do not modify it.
$specialPageAliases = [];

$specialPageAliases['en'] = [
	'AISEOMeta' => [ 'AISEOMeta' ],
];

$specialPageAliases['zh-hans'] = [
	'AISEOMeta' => [ 'AISEOMeta', 'AISEO元数据' ],
];