<?php
// This file is generated by maintenance/generateJsonI18n.php. Do not modify it.
$specialPageAliases = [];

$specialPageAliases['en'] = [
	'AISEOMetaTest' => [ 'AISEOMetaTest' ],
	'AISEOMetaQuery' => [ 'AISEOMetaQuery' ],
	'AISEOMetaBatch' => [ 'AISEOMetaBatch' ],
];

$specialPageAliases['zh-hans'] = [
	'AISEOMetaTest' => [ 'AISEOMeta测试' ],
	'AISEOMetaQuery' => [ 'AISEOMeta查询' ],
	'AISEOMetaBatch' => [ 'AISEOMeta批量生成' ],
];